@echo off
mode con: cols=160 lines=150
cls
color A

echo  ################@#####################################@@@@##@@W@@@@WWWWWMxn##++#nxxxMMxMMxMMMWWW@@WWWMWWMWW@WWW@@@@@@@@@@@@@#@@##################@@@## 
echo  #########################@@############################@#@###@@@@@@WWWWM+i;i*+zn##zznxMxMMMMMMMW@@WWMMWMMW@@@@@@@W@@@@@@@@@@########################## 
echo  ##########################@##########################@######@@@@@@@WWWzi;;i+zxMzznxxxxxMMMMMMMMWWWWMMMWWWW@@@@@@@@@@####@@###@######################## 
echo  ###################################################@@@@####@@WW@@@WMM#ii;*zMWW@WWWWWWMMMMMMMMMMMMMMMMMW@@@@@@@@@@@@@####@##########################@## 
echo  #####################################################@#####@@@@W@@@M+iii*xMM@@@@WWW@WWWWMMMMMMMMMMMxMW@@@@@@@@@@@@@@@@@############################@## 
echo  ###########################################################@@@@@@@W+iii+nWWW@WWWWMWWMMWWWMMMMWWMMMMxxWWWWWW@@@@@@###@@@###@@####################@@#### 
echo  ###################################@@###################@@@#@@@@@W#iii+zW@W@@WWMMxnz##x@@MMWWWMMMMMnnMWWWWW@@@@@@@@@######@@#################@######## 
echo  ####################################@#############@#####@@@@@@@@@n*i*+#M@@WWMxnz#+;:,,;x@WMWWWWWWWWMxMWWWWW@@@@###########@@@######################### 
echo  ########################@@###########################@@###@#@@@@W+i*+#xW@@@Mz+**i;:,,,,*M@WWWWMWWWWWMMWW@@@@@@@@@########@@@@######################### 
echo  ########################@W@########@#################@@###@#@@@@x**+#zW@@@Wn+i;;;:::,,.,#WWWWWWWWWWWWW@@@@@@@@@@@##############@@@#################### 
echo  ######################@######################@###@########@@##@@z+#zzx@@@Wn+ii;;;;:::,,,;MWWWW@WWWW@@@@@@@@@@@##################@##################### 
echo  ##@#######################################@##@@########@@#####@MnzzznM@@Wn+i;;;;;;;:,,..,zWWWW@@@@@@@@@@@@@@@@#@@##################################### 
echo  ##@@######################################@@###########@######@MxnznxW@@M#*;;:::::::,,,,,*WW@@@@@@@@@WW@@@@#############################@##@WW@####### 
echo  ##############################################################WMMnnxM@@@x#*i;;:::::::::;;iM@@@@@@@@@W@@@@@@########@###################@@@@@MM@####### 
echo  ##########################@##################################@WWWnxxM@@Wn#*ii;;iiiii*+nxn#M@@@@WWW@@@@@@############################@######@@@@####### 
echo  ##########################@##################################@@@WnnxW@@Wn#*i+znxnz++#xxn#*nWWWW@@@@@@@@@##@####@@##############################@@##### 
echo  #############@##########################################@####@@@WxnxW@@Wn++nxMMMMx#i+xMMz+x@@@@@@@@#@@@W@######@@#######@@#################@###@@##### 
echo  ########################################################@####@@@Wnzx@@@Wn#zzznxMMM+,;nMM+*x@@@@@@@##@##@@############################################# 
echo  ################@@######################################@@###@@@WnzM@@@Wn##nxWnnMx*,.+nz+;#W@@@@@#######################@@############################ 
echo  #####################################################@#######@@@WnzW@@@Wn#znnxzzx#;,.:+z#;iM@@@#@##################################################### 
echo  ####@################################################@@###@@@@@@WnnW@@@Mz+*++#nx#i;:..,::,,z@@@#####################################################@@ 
echo  @@########################################################@@#@@@@nxW@@@M#*i*#zz*;;;:,......#W@@############@@######################################### 
echo  ##############@#################@@#####@###############@@@####@@@nx@@@@M#*i;;;;:;;::**i:,,,#@@@@@@@W@@@WW@@WW@########@############################### 
echo  ##############@#################@@#####@################@@@@@#@@@xM@@@@Mz+i;::::;;+nxn+:,,:z@@@@@@@@@@@WMW@@@@######################################## 
echo  ################################@#############################@@@MW@@@@Wn#+i;:::::i###i,.,:z@@@##########@############################################ 
echo  ################################@@############################@WWWW@@@@Wn#++*i;;:::;;;::,:;zW@@#########################################@############# 
echo  ###########################################@##################@WWWW@@@@Wn++##+*i;;i+nxxn+i;z@@@#########################################@@############ 
echo  ###########################WW##############@#####@@###########@WMMMW@@@@n+++##+*+znnzz#i;;in@@@@###################################################### 
echo  ###########################@@#######################@######@###WMMMWW@@@x+*+##++++++#zz*;;ix@@@@######@############################################### 
echo  ####################################################@######@###WxMMMW@@WM#+++++++++#zzz*;:+W@W@@###################################################### 
echo  ###########################################@################@#@MxMMMW@@@Wx#+++++++##++*;::nWWWW@############################@@#@###################### 
echo  ########################################################@#@###@xzxMMMW@@@WMz##+++*ii:::,,*MMM@@@@############################@######################## 
echo  @@############################@####################@WMxxMW@@#@@n#nxxxM@@@WWMnz##+i;;;;;;:#MxM@#########@@############################################# 
echo  ################@W#################@@############@Mn++**+#nxMMnz#znxxxM@@WW@WMxn#+*+#zzz#x@MW@#######################@################################ 
echo  ################@@############@#####@@##########@x+++++###zzzz#++#znxnMW@WWW@WMxxxnnxMMMWWWW@@########@@#############@#####################@########## 
echo  ###########################@##@################@n++###++#zzznnz####znxMWWWWWW@WWWWWW@@@@WMWW@@#@@####@W@#########################################@#### 
echo  ################@@@###########################@n#**#zz#+#zznnzzzznnznxxMWMMMWWWMMWW@@@@@WWWW@@@@@###############################################@@@@@# 
echo  ##########@@@####@@####@@####@###@###########@Wnnz#+#znz#znnnzz##znnzznMWMMMMWWMMWW@@@@WMxWWW@@@@@@@############################################@@@@@# 
echo  ###########@@#######@############@@#@########@xnnxxn##znzznnnzz###zxzzzxMMxMMW@MMMW@@@WMxMMW@@@#@@@@@##########@###############################@@WW@#@ 
echo  ###########@########@@###@@#######@@@######@@MzzznxMxz#nnznxnzz###zxnznnxxxxxW@WMMW@@WxMMW@W@@@@@@@@@@#####@###@#############@##############@@@@@xxW@@ 
echo  ###@@####@@###@@@##@@@##########@##@@####@#@@xz++#znxxz#nnnxxnz###znnzznnxMxxW@WWWW@@MxMMWWW@@@@@@#@@@@@@#@@###@######@@@###@@@@@@@@@@@@@@@@@@@@@WW@@@ 
echo  ##@@@@#@@@@@@@@@@@@@@@@@@@@#@#@@@@##@##@@@@@Wxz#**+znxxzznnxxnnz#zznnzznnxxxxxxnxxW@WxxxM@WW@@@@@@@@###@##@@@@@@@@@@@@@@@#@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 
echo  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@###@@Mnzz#**+##zz#znxxxxzzzzznzznnnxxnxxxxxWWMxxxMWMW@@@@@@@@W@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 
echo  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Mzzzz#+*+#####zxMxxxnzzzxnzznnxxxx#nMxMMMxxxxxxW@@@@@@@@W@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 
echo  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@WW@@xz##znz#+#zzzzznMxnnnnnzxnzzznnxxx+#n#xMMMxxnznMW@@@@@@@@@@@@@@@@@@@WW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ 
echo  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@W@@@@@@@@@@WW@Wn####zzzz#+#nnznMxnzzxnnxnzzzznnxxz##nMMMMxxnzzznMW@@@@@@W@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@W@@@@@@@@@WW 
echo  WW@@WW@@@@@@W@@@@@@@WW@@@@@@@@@@@@@@@@@@@@@Wz+#########++#zzxMWMnnnnxnzzznnnnxn+zMMxxxnxxzzz#+zMWWWWWWWWWWWWW@@@WWWWWWWWWW@@@@@@@W@@@W@@WW@W@@WWWWWWMx 
echo  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx+++++#########++zMWWxnnnxnzzznznnxz*nxxxxxnMxnzzz#+#nxMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWW 
echo  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMn++++++####zzzzz#+#nnznnnnnzzznznnxz+nxxxxnxMxnz#zz###+#nMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWW 
echo  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMz+++++++#######zzz##+nnnnznnzznzznn#izxxxnnxMnnn##zz###z#nMMWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWMMW 
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxz+++++++#######++###zznnznnnzznnzznz#nxxxnnMMnzn##nnzzzzzznMMMMMMMMMMMMMWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
echo  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxMn#+*++#######++++***+znnznxnnzzzzzzn+zxxxnnnMxnzzz#nnnnzzznznMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 
echo  MMMMMMMMxxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMnxMz++*+#########++++#znxMxnxxnnzzznzzn*#xxxnnnxxnzzzzzzxxnnnz#znxMMMMMMMMMMMMMMMMMMMxMMMMMMMMMMMMMMMMMMMMMMMMM 
echo  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxnxMz#+*+#zzz#####+++#nMWWWMxxxxnnzznzzn*#xxxnnxxxnzzznxnxMnznz#znxxxxMxxMxxxMMxxxxxxxxxxxxxxxxMMxxxMxxxMxxxxxxx 
echo  nnxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxnnMMz##++##zzz#######zznxWWMMMMxxnnnnzzn*#xxnnnxxnnzzznxMzz+znzzzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
echo  nnxxnnxxxnxxxxxxxxxxxxxxxxxxnxxxxxxxnnxxMMz+++##zzz######zznz+++znxMMMxxxxxnnn+zxMnnxxxnnznznxMWMxxnnn#nxxxxxxxxxxxxxxxxxxxxxxxxxxxxnnxxxxxxxxxxxxxxxx 
echo  nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnxxMMz#+++#zzzz####zzznnz#+*i*nMMMMMxxxnn+nMxnxxxxnnnnnxMMMMWxnnn#znnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn 
echo  nnnnnnnnnnnnnzznnnnnnnnnnnnnnzznnnnnnnnxMMn#+++#zzzzz##zzzzzzz#++##zz#zxMxxxxn#nMxnxxxxnnnnnxMMMMMxxxnz+znnnnnnnnnnnnnnnnz#znnnnnnnnnnnnnnnnnnnnnnnnnn 
echo  zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzxxxMM##++#zzzz###zzzzzzzznxxxMMMxnxxMxxnzxMxxxxxxnnnnnxMWMMxxMMn#*#zzzzzzzzzzzznnzzzzzzzzzzzzzzzzzzzzznzznzzzzzz 
echo  zzzzzz#zzz##zz#zzzzzzzz####zz####zzzzxxxxWMz##+zzzzzzzzzzzzznnxxMMMMMxn#nMMxxznMMxxxxxnnnnnnMMWWMxMWxz+++zzzzzzzzzzzzzzzzzzzzzz##zzzzzzzzzzzzzzzzzzzzz 
echo  ##########################++########zxxnnMMz####znnzzznnzzzznnnxxxxxxn#++nxn##nMMxxxxxnnnnnnMWWWMWMxz###+#############+########+###################### 
echo  +++++++++++++++++++++++++++++++++++#nxnzxMMz#z##znnnnnnnnznzzzzz###++***+#####+nxxxxxxxnnnnnMWWWMMn##zzz++#############+##+++######################### 
echo  +++********++++*****+****+++++**++++zxnnxxxzzzz##znnnnnnnzzzzz######zznnnxxxnz#++zxxxxxxxnnnMWWWx#zxxznx#+++++++++++++++++++++++++++++++++++++++++++++ 
echo  ************************************#nnxMMx#zzzzzzznnnnnnzzznnnxxMMMMMMMMxxxxnzz##+#zxxxxxxxWWWMnnMxznMxz********************************************* 
echo  iiiiiiiiiiiiiiii;iiii;i;;;i;;ii;iiii*nxMMMx#znnzzzzznnnnzzznnnxxMMMWWWWMMMxxxnnnnnnz+#xMxxMMW@WxnxMnnMMx#*iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii 
echo  ;;;::::;::::::;:::::::::::::::::::::;nMMMMWzzxnnzzzzznnnzznnxxxxxxMMMMMWMMMxxxxxxxxnz#xMMMMMW@MnxWxnMWMz#i;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; 
echo  ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;xWWMxMnzxxnnnnnnnnzznnxxxxxxxxxxxxMMWWMMMxxxxxxxnnMMMMW@@MxMMnxWMn##i:,,,,,,,,,,,::,,::,,::,,,::::::::::::::::::: 
echo  .............................`......*MWWxnxnnxMxnnnnnnnznnxxxMxxxxnnxxxxxxMMMWMMMxxxxnxMMWMW@@WMWxnMMnzxn*,........................................... 
echo  ```````````````````````````````````,zWWMxxxnnxMMxnnnnnnnnxMMMMMMMMxxxxxxxxxxMMMMMxxxxxxMMMM@@@WWMnnnznMMx#:``````````````````````````````````````````` 
echo  ,,..,,,,,,,.,,,,,,,,.,,,,,,..,,,,,,ix@MMxxxnnxMWMxnnxxxxMMMWWWWWWWWWMMMxxxxxxxMMMMMxxxMWMMMW@@WWxzznxMMnzz*,.,,,,,....,,,,,....,,,,,.....,............ 
echo  .........,,.......,,,.......,,,.,.,+xWMMxxxxnxMWWMxnxMMMWWWW@@@@W@@@@WWWMMMxxxxxxxMMMxMWWMMzxW@WnnnxMMxzzn+:.....,,,,.....,,,,.....,,,,,.....,,,.,..., 
echo  ....,.,,......,,.,........,.,.....izxMMMMWWMnxnMMWMxxMWWW@@@@@@@@@@@@@@@@@WWWMMMMMMMMMWWWMMnizWMnnxMMnzzxx#;,.......,,,,......,,,........,,,........,, 
echo  ,.,,......,,,,,.....,,,,,,,....,,:#nMWMWxMMnnn#izWWMMMWWW@@@@@@@@@@@@@@@@@@@@WWWWMMMMMWWWWWMi:nxnnnzz#zxMMz;,,,,,.....,,,,,....`.,,,,,.......,,,...... 
echo  ......,,,,,......,,,,,,,.....,,,,:#xWWMMxxxnzxxzxW@@WWW@@@@@@@@@@@@@@@@@@@@@@@@@WWWWWWW@@@@W#:izznnnz##znnzi...,,,,,.,....,.,,,..,....,,,,,..,....,,,, 
echo  .,,,,,,,,,....,,,,,,,,,...,,,,,,,;zMWMxnxxxnnMWMW@@WMW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@WW@@@@@Wn++znxxxMxxnzzz*:,..,,,,,,,,,,,..,,,:,,,,,,...,,,,,,.,,... 
echo  ::,,,,,..,,::::,,,,,..,,:::,,,,::izMWxnxxMxnnxMW@WxxMW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@Wnnz###znnxMxxzz+:,,,,...,:::::,,,,,..,,,::,,..,,...,,,,,,. 
echo  ,,...,,,,,,,,,,,,..,,,:,,,,,,,:,.inMxxxxMMMxzin@WnnMW@@@@@MMMWW@@@@@@@@@@@@@@@@@@@@@@@@@@@W@Wxxxnz##zznxxnz+:,,,,,....,,,,,,,,,,..,..,,,,,,,,...,,,,,, 
echo  ...,,:::::,,,,,,..,,::,,,,,,,,..,*xnnxMMMWWMxnMWxnxWWWW@@@Wn##znnxxMMWW@@@@@@@@@@@WWWW@@WWMxMWxnxnnnznnnxxn+;::::::::,..,:::::::::::,..,::::::::::,,., 
echo  ::;;::::::::,,,:;;;;;;:::;;:,,:;;+xnxxMMMMMxxW@MnnMWWWM@@@@Wxz#zzzzzznxW@@@@@@@@@WWMMMWWWMMxxxMnnxxxxxxxxxx#i:::::::,,,,:,.,,:,,,,,,,,,,,..,,,,,,,,,.. 
echo  :,,,,,,,,,...,,,,,,,,,,,,,,...,,,innxMMMxxxxMMWxnxMMMMMW@@@@@WMnzzzzzznW@@@@@@W@WWMMMMWWWMMMMMxnnnxxxMMxxxxz;,:::::::::::::,.,:::::::::::::,.,:;;;;;;; 
echo  :,,:::,..:;;;;;;;::::;;:,,:;;:;;;*nxxMxxxxxxMMMnxMMxxMMWWW@@@@@@MxnzzznW@@@@WWWWMxxxxxMMMMMMMWWWMxzzznxMxxxni,.,:::::::::,,,::,.,,,:::,,,,,,,,,,...,,, 
echo  ::::,..,:::::::::,::::,.,::::::::inxxxnnxMxxMMxnMMxxxMMWWW@@@@@@@@WxnnxW@@WWWWWWMxxxxxxxxMMMWW@@WWMxnnnxMxxn*;:,,:;;;;;i;;;;;;;;:,,:;i;;;ii;;;;;;::,,: 
echo  ,..,,.,,,,,,,,,,,::,..,:::::::::,;nMxnzxxMMWWMnnxxnxMMMWMM@@@@@@@@@@WMWW@@@@WWWWMMMMMMMxnnxxMWW@@@WWMMxxxMxn;,,,,...,,,,,,,,,,,.,.......,,,,,,,,,,,... 
echo  ,:;;;::;iii;;;;iii:,:;**iiiiiiii;izMxnxMMMW@WMxzznnMWWMMMM@@@@@@@@@@@WW@@@@@@@@WMMMWWWWMxnzznxMWWWWWWMMMMxxn+;;iii;,,;iiiiiiiii;;;;ii;,,:;;;;;;;;;;::: 
echo  :::::,,:,,,,,,::,..,::::::::::,,,:#xxxMMWW@WMWxzznxWWMMMMMW@@@@@@@@@@@@@@@@@@@@WWWWWWWWWWMxxnznxMMWWWMMMMxxn*:::::;:,.,:;;;;;;;;;;:;;;;:,,,;;;;iiiiii; 
echo  :::::::,,,::::,.,::::::::::::,::::+xxMMWW@@MMWnznxMWWWWMMMWWW@@@@@@@@@@@@@@@@@@@WWWWW@@@WWWWMxnnnxxMMMMMMMx#;:::,,,,,,,..,,,,,,,,,,,,..........,,,,,,, 
echo  iiiii;;;iiii;,:;ii*iiiii*iii;;iiii*xxMWW@@WxWMzzxMWWWMMMWWWWWWW@@@@@@@@@@@@@@@@@@@@@@@@@@@@@WWMMxxxxxxxxxMxz*i**ii;;iiii:,:;iiiiiiiiii;;;;ii;:,,:;;;;; 
echo  iii;;;iiii:,,;iiiiiiiiiiii;;;iii;:*nMWWW@WxxMn#zxWWWWxMWWWWWWWWW@@@@W@@@@@@@@@@@@@@@@@@@@@@@@@@WWMMxxxxxMMx#******ii;iiii;:,;iiiiiiiiiiiii;;iii;:,:iii 
echo  ,,,,,,,,,...,,,,,,,,,,,,,,,,,,,,.,#MWWWWWWxxxzzxMWWWxxMWWWWWWWWW@@@WW@@@@@@@@@@@@@@@@@@@@@@@@@@@@WWWWWWWWW#::::::::::::::::,..::::::::;;;;;:::;;;::,,: 
echo  ::;;;;:,,:iiiiiiiiiiiii;;;::;i;,,*xWWWWWWMnnnzxMMWMxxMMMWWWWWMMWWWWWW@@@@@WW@@@@@@@@@@@@@@@@@@@@@@@@@@@@Wni;;;;;;;;;;;::,:::::,.,::,,:,:::,,,,,,,,,,,, 
echo  i**i;:,:iiiiiii******ii;ii;;i;,:izMW@@@@MnnnznxMMMxxxMMMMWWWMWMMMWWWWWWWWW#x@@@@@@@@@@@@@@@@@@@@@@@@@@@@x+*iiii*******iiiiiiiii;,,;;iiiii***iiiii;;iii 
echo  *i;,,;i*************iiiiiiii;,:i*xWW@@@WxznxnxMMMxnxMMMMMMMWMWMMMMMMWWWWWM#xWW@@@@@@@@@@@@@@@@@@@@@@@@@M+:;iiii**********ii;iiii;:,:;iiiiii*iiiiii;i;i 
echo  ;:,:;iiiii*********iiiiiii;:,:ii+xW@@@WMnnxxxxMMxxMMMMMMxMMMMMMMMMMMMWWWWWnxWMWWW@@@@@@@@@@@@@@@@@@@@@Wz*;,:i****++++++*****ii**iii;::i**************i 
echo  ..,,::,::::::::::,,::::,,,,,,:::+xMWWWWxnnxxxMMxxxMMMMxxxxMMMMMMMMMMMMWMWMxMMMMMMWWWWWW@@@@@@@@@@@@@@@xi:,,,,,,,:::::::::;:::::::::::,,:;;;;;;iiiiii*i 

color A
@echo off
:A
set /p Enter=">"
%Enter%
goto :A